# Generated by Django 4.1.5 on 2023-02-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.IntegerField(unique=True)),
                ('identification_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('mobile_phone', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_history',
            fields=[
                ('ailment', models.CharField(max_length=50)),
                ('hospitalization_history', models.CharField(max_length=50)),
                ('hospitalization_cause', models.TextField(blank=True, null=True)),
                ('medication_use', models.CharField(max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clinic_management.patientpersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('invoice', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('doctor', models.CharField(max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clinic_management.patientpersonalinfo')),
            ],
        ),
    ]
